[project]
name = "mono"
default_pipeline = "ci"

[pipelines.ci]
tasks = ["changelog-check", "fmt", "check", "test", "clippy"]

[tasks.changelog-check]
command = ["cargo", "run", "--locked", "--quiet", "--", "changelog", "check"]
timeout_seconds = 30

[tasks.fmt]
command = ["cargo", "fmt", "--check"]
timeout_seconds = 30

[tasks.check]
command = ["cargo", "check", "--workspace", "--all-targets", "--all-features"]
depends_on = ["fmt"]
timeout_seconds = 120

[tasks.check-docs]
command = ["zensical", "build"]
timeout_seconds = 120

[tasks.test]
command = ["cargo", "test", "--workspace", "--all-targets", "--all-features"]
depends_on = ["check"]
timeout_seconds = 120

[tasks.clippy]
command = ["cargo", "clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]
depends_on = ["test"]
timeout_seconds = 120

[tasks.changelog]
command = ["cargo", "run", "--locked", "--quiet", "--", "changelog", "prepare"]
timeout_seconds = 60
