[package]
name = "web"

[tasks.build]
command = ["echo", "[web] build after api:build"]
depends_on = ["api:build"]
timeout_seconds = 30

[tasks.test]
command = ["echo", "[web] test after build and api:test"]
depends_on = ["build", "api:test"]
resource_group = "checks"
timeout_seconds = 30

[tasks.package]
command = ["echo", "[web] package"]
depends_on = ["test"]
timeout_seconds = 30
