[package]
name = "api"

[tasks.build]
command = ["echo", "[api] build"]
timeout_seconds = 30

[tasks.test]
command = ["echo", "[api] test"]
depends_on = ["build"]
resource_group = "checks"
timeout_seconds = 30

[tasks.package]
command = ["echo", "[api] package"]
depends_on = ["test"]
timeout_seconds = 30
